apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-app
  labels:
    app: hotstar-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotstar-app
  template:
    metadata:
      labels:
        app: hotstar-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: hotstar-app
        image: veeranarni/hotstar:latest
        #image: nginx 
        #image: syncomm/netflix
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
